### PR TITLE
Add support for GitHub token stored using "plaintext" credentials

### PR DESCRIPTION
**Pull request by langecode**
This change extends the `Connector` class to support token based authentication against the GitHub API using token stored as secret text in the plaintext credentials plugin.

### CODE REVIEW

**Comment by jglick** [comment]
> using username and password is blocking adoption right now

That does not seem plausible. You can already use GitHub personal access tokens. [Example](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/demo/README.md)

**Comment by langecode** [comment]
Yes, it should also be possible to do basic auth with a token, however I wanted to avoid using basic auth due to some limitations in our corporate infrastructure.

**Comment by szakrewsky** [comment]
Thanks @jglick @langecode, using the personal access tokens works fine for me.

**Comment by bitwiseman** [comment]
@langecode @jglick 
Is this PR still valid or should we close?

**Comment by jglick** [comment]
From my perspective it can be closed, perhaps with some UI/docs adjustments to make it clearer that you can use PATs in “username/password credentials”.

**Comment by bitwiseman** [comment]
Filed https://issues.jenkins-ci.org/browse/WEBSITE-627.

**Pull request closed without merging**
