### PR TITLE
Added logging about webhooks received and how they are processed

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee:

**Comment by recena** [comment]
@jglick I'm doing tests with this PR in order to see the result of this messages.

**Comment by mslusarczyk** [comment]
🐝

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
I have a customer log using this patch in which the _…forwarded to…_ message appears as expected.

**Comment by recena** [comment]
@jglick If you had the chance to verify that the logs are working as expected, we can merge this one, right?

**Comment by jglick** [comment]
Yes I think so.

**Pull request merged**
