### PR TITLE
[JENKINS-33623] Fix incorrect proxy handling

### PR DESCRIPTION
**Pull request by schulzh**
[JENKINS-33623](https://issues.jenkins-ci.org/browse/JENKINS-33623)

Basically the same bug as https://github.com/jenkinsci/github-plugin/pull/109: The Jenkins ```ProxyConfiguration``` class expects only the hostname as a method parameter to ```createProxy```, but the existing code gives it the whole URL.

### CODE REVIEW

**Comment by schulzh** [comment]
@recena I hope you don't mind the mention to draw some attention to this PR (you seem to be quite active in this project)

**Comment by recena** [comment]
@schulzh Let me take a look. Could you include a link to the Jira issue?

**Comment by schulzh** [comment]
@recena There is no Jira issue, at least AFAIK. I just had this problem on our server and found out what was wrong, so I fixed it.

**Comment by recena** [comment]
@schulzh Please, assign the Jira issue yourself and change its status.

**Comment by schulzh** [comment]
@recena Done.

**Comment by schulzh** [comment]
@recena Could you merge this PR? I don't have the necessary authorization to do so.

**Comment by DeltaLikeM** [comment]
+1

**Comment by kenshi90** [comment]
+1

**Comment by berndhofmann** [comment]
👍

**Comment by SuperSpectre** [comment]
👍

**Comment by recena** [comment]
@schulzh I hope to merge this PR today.

**Comment by schulzh** [comment]
@recena Any updates on this?

**Comment by recena** [comment]
@schulzh I'm sorry for delaying this.

**Comment by recena** [comment]
@schulzh I'm sorry for delaying this.

**Comment by recena** [comment]
@schulzh I'm sorry for delaying this.

**Comment by DeltaLikeM** [comment]
@recena Any updates on this?

**Comment by recena** [comment]
I've prepared this PR https://github.com/jenkinsci/github-branch-source-plugin/pull/58

**Comment by recena** [comment]
This [PR](https://github.com/jenkinsci/github-branch-source-plugin/pull/58) supersedes this one.

**Pull request closed without merging**
