### PR TITLE
[JENKINS-43806] - Ability to exclude commit author (system user) from triggering builds

### PR DESCRIPTION
**Pull request by wykapedia**
Enhancement to allow users to exclude authors from preventing builds.
[JENKINS-43806](https://issues.jenkins-ci.org/browse/JENKINS-43806)

### CODE REVIEW

**Comment by ctoestreich** [comment]
:+1:

**Comment by acejam** [comment]
Patiently waiting for this feature, looks great!

**Comment by wykapedia** [comment]
Looks like this may be dependent on another issue being fixed first:
[JENKINS-36195](https://issues.jenkins-ci.org/browse/JENKINS-36195)

**Comment by acejam** [comment]
@wykapedia Have you tested your changes in this PR? Do they work? The ticket you linked appears to be related to polling, not webhooks, no?

**Comment by wykapedia** [comment]
Looks like you may be right @acejam.  The Jenkins issue listed above is related to polling and not web hooks.  It looks like it is not possible to add excluded users to a web hook at this point.  Perhaps, there will be an enhancement on the Jenkins side which will allow the "UserExclusion" that I added to avoid triggering builds when GitHub notifies Jenkins of the build.

**Comment by stephenc** [comment]
Fundamentally this approach will not work. What is wanted is the concept of interesting branches and interesting revisions (see [JENKINS-45502](https://issues.jenkins-ci.org/browse/JENKINS-45502)) then you could implement a filtering trait that reduces the interest in revisions that are from authors you do not want automatic builds from.

**Pull request closed without merging**
