### PR TITLE
[FIXED JENKINS-46295] Handle the case where the query optimization is for a deleted branch

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-46295](https://issues.jenkins-ci.org/browse/JENKINS-46295)

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by acejam** [comment]
@stephenc Can we get a release cut of this plugin so I can deploy this fix?

**Comment by stephenc** [comment]
rolling 2.2.4 right now... hopefully it will release no problem and you should be able to see it in the update centers in a couple of hours

**Pull request merged**
