### PR TITLE
Use upstream Spotless configuration

### PR DESCRIPTION
**Pull request by basil**
Now that the upstream plugin parent POM has a formatting profile, I am trying to adapt as many consumers to use it as possible. This repository was an early attempt at automatic formatting that used a different configuration. I do not think anyone is particularly attached to it, and maintenance would be easier moving to our project-wide standard. @jglick Any interest in merging this? I would not be upset if this PR is rejected, but if this repository is to continue using Spotless I think it would benefit from using a more standard configuration. If accepted I will add a `.git-blame-ignore-revs` file after this is merged.

### CODE REVIEW

**Comment by jglick** [comment]
More legible (IMO) than #392. I do not believe @bitwiseman remains active in Jenkins. I will ask around to see if anyone claims to maintain this plugin.

**Comment by jtnord** [comment]
not until sptless is not brain dead on windows with check-out as is and check in as is please.

**Comment by basil** [comment]
The Windows CI build is fine.

https://groups.google.com/g/jenkinsci-dev/c/zUewd9LL5-g/m/PM21Kb0TAQAJ

**Comment by bitwiseman** [comment]
@basil @jglick 
No I'm not active in Jenkins at this time.  FWIW, my original goal for using spotless was to not have any more discussions or PR comments regarding formatting.  This change seem to be aligned with that goal.

**Review by jglick — APPROVED** [review]
Consistent with other repos.

**Comment by jglick** [comment]
(@rsandell @car-roll FYI, since you both have active PRs.)

I will merge this and follow up with an addition to `.git-blame-ignore-revs` as in #528.

**Comment by basil** [comment]
I can help with merging this change into existing branches if needed.

**Comment by basil** [comment]
- #701 has been filed to add a `.git-blame-ignore-revs` file to this repository
- #698 has been merged with this PR at https://github.com/basil/github-branch-source-plugin/tree/private-mode-rate-limit
- #699 has been merged with this PR at https://github.com/basil/github-branch-source-plugin/tree/JENKINS-70163-proxy-selector
- #700 has been merged with this PR at https://github.com/basil/github-branch-source-plugin/tree/JENKINS-69815

**Comment by jglick** [comment]
Rough merge instructions FTR

```bash
git merge 51545c3^
git stash apply
mvn spotless:apply
git checkout HEAD -- pom.xml
gh pr diff --name-only | xargs git add
git commit -m 'Spotless like in #684'
git reset --hard HEAD
git merge -Xours 51545c3
git pull origin master:master
```

with the stash

```diff
diff --git pom.xml pom.xml
index f1b8ba8..58b01c0 100644
--- pom.xml
+++ pom.xml
@@ -4,7 +4,7 @@
     <parent>
         <groupId>org.jenkins-ci.plugins</groupId>
         <artifactId>plugin</artifactId>
-        <version>4.16</version>
+        <version>4.61</version>
         <relativePath />
     </parent>
     <artifactId>github-branch-source</artifactId>
@@ -135,63 +135,6 @@
             </dependency>
         </dependencies>
     </dependencyManagement>
-    <build>
-        <plugins>
-            <plugin>
-                <groupId>com.diffplug.spotless</groupId>
-                <artifactId>spotless-maven-plugin</artifactId>
-                <version>2.8.1</version>
-                <executions>
-                    <execution>
-                        <id>spotless-check</id>
-                        <!-- runs in verify phase by default -->
-                        <goals>
-                            <!-- can be disabled using -Dspotless.check.skip=true -->
-                            <goal>check</goal>
-                        </goals>
-                    </execution>
-                </executions>
-                <configuration>
-                    <java>
-                        <googleJavaFormat>
-                            <style>GOOGLE</style>
-                        </googleJavaFormat>
-                    </java>
-                </configuration>
-            </plugin>
-        </plugins>
-    </build>
-    <profiles>
-        <profile>
-            <id>ci-non-windows</id>
-            <activation>
-                <property>
-                    <name>set.changelist</name>
-                </property>
-                <os>
-                    <family>!windows</family>
-                </os>
-            </activation>
-            <build>
-                <plugins>
-                    <plugin>
-                        <groupId>com.diffplug.spotless</groupId>
-                        <artifactId>spotless-maven-plugin</artifactId>
-                        <executions>
-                            <execution>
-                                <id>spotless-check</id>
-                                <!-- In CI, run check early in the build -->
-                                <phase>process-sources</phase>
-                                <goals>
-                                    <goal>check</goal>
-                                </goals>
-                            </execution>
-                        </executions>
-                    </plugin>
-                </plugins>
-            </build>
-        </profile>
-    </profiles>
     <repositories>
         <repository>
             <id>repo.jenkins-ci.org</id>
```

**Pull request merged**
