### PR TITLE
Use the GitHub logo instead of other icons

### PR DESCRIPTION
**Pull request by janfaracik**
# Description

Small change to use the GitHub logo (as a [Jenkins Symbol](https://weekly.ci.jenkins.io/design-library/Symbols/)) for sidebar actions. IMO using the one icon verses the couple currently in use makes it more consistent and understandable what the link does at a glance.

**Before**
image

**After**
image

(Pardon the screenshot quality)

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Automated tests have been added to exercise the changes
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed

# Users/aliases to notify

### CODE REVIEW

**Comment by NotMyFault** [comment]
The GH logo is available in the ionicons API too, isn't it?

**Review by jtnord — CHANGES_REQUESTED** [review]
do we have written approval to do this?

https://github.com/logos

>  Do not use GitHub trademarks, logos, or artwork without GitHub’s prior written permission.

IANAL - but the do not contradicts the Do.

**Comment by jtnord** [comment]
This also incorrectly (IMO) changes the logo used in the title of the project - it should only (if approved by GitHub) be used in the sidebar link AFAICT)

image

**Comment by jtnord** [comment]
FTR - inverted colours dark theme

image

**Comment by NotMyFault** [comment]
> https://github.com/logos

The icon is part of the icon set named "ionicons" (https://ionic.io/ionicons) licensed under MIT.

**Comment by jtnord** [comment]
> The icon is part of the icon set named "ionicons" (https://ionic.io/ionicons) licensed under MIT.

it is a trademark of GitHub and as such trademark rights apply - we do not care about the licence of the actual vector.

**Comment by jtnord** [comment]
https://support.github.com/ticket/personal/0/2234467 created to seek approval from GitHub for the use (which is both allowed and not allowed at the same time) but also for inverting for the dark theme.

**Comment by jtnord** [comment]
GitHub responded - as there are 2 logos in their download (`mark` and `mark-white`) - we would be okay for the dark them as long as we are using those colours.

I still beleive we need to revert the icon change for the display of the project name - which seems unintentional based on the PR description and also does not appear to correspond to the usage requirements.

**Comment by janfaracik** [comment]
> GitHub responded - as there are 2 logos in their download (`mark` and `mark-white`) - we would be okay for the dark them as long as we are using those colours.
> 
> I still beleive we need to revert the icon change for the display of the project name - which seems unintentional based on the PR description and also does not appear to correspond to the usage requirements.

I've updated the PR to align with this - pipelines will now use their original folder icon rather than the GitHub logo. Thanks

**Review by jtnord — APPROVED** [review]

**Comment by puetzk** [comment]
Just to make the error message more googleable: this change (seemingly quite intentionally) results in the "Manage Old Data" tab showing lots of warning messages
> CannotResolveClassException: iconClassName

For data in config.xml which previously looked like
```
          <org.jenkinsci.plugins.github__branch__source.GitHubLink plugin="github-branch-source@1767.va_7d01ea_c7256">
            <iconClassName>icon-github-branch</iconClassName>
            <url>https://...</url>
          </org.jenkinsci.plugins.github__branch__source.GitHubLink>
```

Because these `icon-github-logo` and `icon-github-branch` classes were indeed remove.

**Pull request merged**
