### PR TITLE
Switch to standard <f:select>

### PR DESCRIPTION
**Pull request by jsoref**
This reverts to `<f:select>` as [JENKINS-42443](https://issues.jenkins-ci.org/browse/JENKINS-42443) was fixed a while ago (and the current required version is `<jenkins.version>2.121.3</jenkins.version>`). The feature in question was added in 2.50 (2017-03-11).

Unfortunately, afaict it never worked properly.  So this shouldn't be integrated until jenkinsci/jenkins#3918 is in LTS and this plugin's jenkin version is bumped again.

### CODE REVIEW

**Comment by jsoref** [comment]
So, while the basic code is present, the spinner appears to not work.

```
#jenkins .jenkins-config table td select {
  border-radius: 0;
  background: #ffffff;
}
```

I'm not sure where this is, but that background is more specific than the rule for the spinner and thus the spinner loses.

**Comment by rsandell** [comment]
So this should not be merged then? Or what are you saying?

**Comment by jsoref** [comment]
@rsandell: the upstream feature that handles this properly was released in [https://jenkins.io/changelog/#v2.167](2.167)
but it hasn't reached [https://jenkins.io/changelog-stable/](LTS).
If you want to wait for it to reach LTS before merging, you can, otherwise you could merge today.

**Comment by bitwiseman** [comment]
@jsoref 
What happens if this change is used on Jenkins versions before 2.167 where the upstream feature was released?

**Comment by jsoref** [comment]
1. Users click on dropdown (?) ...
1. Browser is told by jenkins to retrieve content for dropdown
1. Browser is half-told that maybe it should show a spinner.
1. No spinner is actually shown because the css is too weak.
1. (time passes)
1. Content returns from server and is rendered

**Comment by bitwiseman** [comment]
@jsoref 
So, if we merge this before this before the fix gets into LTS we'll see some poor behavior. It will be about another month before a post 2.167 lts happens I believe.   We should wait until then.

It that okay?

**Comment by jsoref** [comment]
Fine by me

**Comment by bitwiseman** [comment]
2.176.1 is out. Merging.

**Pull request merged**
