### PR TITLE
Coding style

### PR DESCRIPTION
**Pull request by recena**
@reviewbybees 

_Details, always details._

### CODE REVIEW

**Comment by KostyaSha** [comment]
@recena you can add checkstyle with minimal set of rules, if you need some examples then i can help + it would be possible to post automatic comments.

**Comment by recena** [comment]
@KostyaSha I know it, I'm a big fan of everything related to code conventions I hope to convince @jglick for using something similar.

**Comment by amuniz** [comment]
:bee:

**Comment by stephenc** [comment]
:bee: and you know my position on some people's claims of coding style ;-)

**Pull request merged**
