### PR TITLE
[JENKINS-46119] Add GitHubStatusContextProperty support

### PR DESCRIPTION
**Pull request by c9s**
Add GitHubStatusContextProperty to support github build status context customization

This is to let user customize the github build status context from their pipeline.

## Screenshots

image

image

## Issues

Related issue: JENKINS-36574, JENKINS-46119

### CODE REVIEW

**Comment by rmg** [comment]
Isn't the `pending` status set before the pipeline script is read? The screenshot seems to confirm that, showing that setting the context in properties will result in a pending status that would never be updated.

🤔 I guess that would actually only happen on the first build of the PR since after that the property would already be set on the job.

**Comment by c9s** [comment]
@rmg yes you're correct, I am considering moving the property to BranchProperty

**Comment by c9s** [comment]
BranchProperty done, Screenshot updated. You can now customize the branch build context from the project configuration page.

**Comment by c9s** [comment]
ping @rsandell

**Comment by c9s** [comment]
ping @jglick and @stephenc

**Comment by stephenc** [comment]
https://plugins.jenkins.io/github-scm-trait-notification-context being the extension plugin I think that does what you are trying to do (unless I misunderstand)

**Comment by c9s** [comment]
@stephenc 

yes, I know there is an extension doing this, but I think this enhancement should be done in the github-branch-source plugin since this plugin already provides the build status notification feature. And the branch property code is really just a few lines of code, this helps people to customize the context.

> Why do these changes make sense for all users?
The scenarios is like, you have more than one complex pipeline flows defined in your project, and you created two multi-branch project that clones the same source code repository but runs different jenkinsfile for purpose.

If the status context can not be customized, there will be an issue:  every Jenkins job that clones the same source will update and override the status to the same context, which is causing problems.

**Comment by stephenc** [comment]
This is not a core feature. Core features are expensive to release. Extension plugins are much cheaper to release. Only exceptional UI changes belong in core. How does this change differ from that in the extension plugin? Would making the change here compete with the extension plugin?

If you cannot provide compelling answers to those questions then we should close this PR

**Comment by stephenc** [comment]
@bitwiseman the change itself is fine, the problem is that it should be in the extension plugin not here... unless someone can provide a compelling reason for exposing everyone to this increased complexity (rather than only exposing the people who opted in to increased complexity by installing the extension plugin)

**Comment by bitwiseman** [comment]
@stephenc 
On review of JIRA, I'm finding multiple high priority issues asking for for this feature. 
It is fine to say that a feature should be done as a plugin, but in this case the increased complexity is specific specific to this plugin.  Putting in another plugin add to user pain and confusion for only theoretical benefit.

**Comment by bitwiseman** [comment]
For posterity - This plugin does the same as this PR: 
https://plugins.jenkins.io/github-scm-trait-notification-context

**Pull request closed without merging**
