### PR TITLE
[JENKINS-34395] Support for building tags

### PR DESCRIPTION
**Pull request by tanskann**
Adds support for building tags/releases.

### CODE REVIEW

**Comment by s-pk** [comment]
@tanskann Would you want to solve some of the merge conflicts here? I'd love to have this merged in, but I'm sure the maintainers won't take a look until some of those issues are fixed.

**Comment by tanskann** [comment]
Have to close this since I don't have time to fix this. Will come back to it later. Sorry @s-pk :/

**Comment by gena01** [comment]
@tanskann @stephenc what is left to get this working? Looks like current master already has a lot of the pieces for this except the configuration and the "BranchDiscoveryTrait"? Or did I miss something else?

**Comment by stephenc** [comment]
So ideally to support tags I think we need to add the concept of interesting revisions: [JENKINS-45502](https://issues.jenkins-ci.org/browse/JENKINS-45502)

In any case somebody would need to write the actual code that I put TODOs as placeholders for.

Then the question of whether the TagDiscoveryTrait should live in this plugin or a separate extension plugin also arises.

In principle, I am not against TagDiscoveryTrait in this plugin, but I would rather see [JENKINS-45502](https://issues.jenkins-ci.org/browse/JENKINS-45502) addressed beforehand... as a stop-gap there are [some changes in branch-api that could prevent tags from being built automatically](https://github.com/jenkinsci/branch-api-plugin/commit/cf848af4addf33f0aae9c86149fc0cfd1fee5c82) so if they actually work (as opposed to working in theory - with a test) then we might not need to wait for JENKINS-45502

The real risk is what happens when you clone a repo that has existing tags... and when the existing Jenkinsfile has a condition to deploy to production if building on a tag... and the tags get discovered in random order...

I also think TagDiscoveryTrait should probably be configurable with a time cut-off, e.g. only discover tags less than 6 months old (that will drop off very old tags too)

**Pull request closed without merging**
