### PR TITLE
#JENKINS-54992 Change pronoun

### PR DESCRIPTION
**Pull request by michaelneale**
Change pronoun to reflect it is a pipeline regarding: https://issues.jenkins-ci.org/browse/JENKINS-54992

and avoid scary messaging

### CODE REVIEW

**Comment by michaelneale** [comment]
@rsandell @stephenc for arguing about (see linked issue)

**Comment by rsandell** [comment]
So let the arguing commence :)
Though "Pipeline" is currently the only implementation of a branch source consumer it is not the intent.
I may prefer a more general name change, like _Job_.

**Comment by bitwiseman** [comment]
This looks good to me.  No one has felt the need to argue against this.

**Comment by rsandell** [comment]
@bitwiseman I did :)

**Comment by bitwiseman** [comment]
@rsandell 
Ah, okay.  Well, regardless of the intent, it is currently and for the foreseeable future the only consumer of branch source.  I suggest that we make this change and leave it to that hypothetical future consumer to come up with better text.

**Comment by stephenc** [comment]
Cough “literate” cough

**Comment by bitwiseman** [comment]
@stephenc 
cough - What does that one word mean in this context? - cough.

**Comment by michaelneale** [comment]
@bitwiseman he means that terrible idea he (and I, share the blame somewhat) had in, what, 2013? also in theory uses branch source. or was it 2011?

**Comment by stephenc** [comment]
Branch source was created for the literate-plugin

**Comment by michaelneale** [comment]
@bitwiseman no idea - maybe @rsandell ?

**Comment by bitwiseman** [comment]
@michaelneale 
Yeah, I'm not saying you're wrong.  

I'm saying, what this means is that this text would need to be changed for each of the available branch sources.  Is there some other place (in the multi-branch pipeline plugin) where a change could be made that would fix this for Multi-branch regardless of source?

**Comment by michaelneale** [comment]
@bitwiseman not sure - they could all be changed to use a general one, but then some branch sources (if we are being technical) don't actually call it a repository (git based ones do obviously). Could boil the ocean but the only place people complained they were worried it would delete their github repo was.. here - in github!

**Comment by stephenc** [comment]
Sounds like the fix is to just override the `Delete {0}` text in branch-api then.

**Comment by bitwiseman** [comment]
@stephenc  Overriding it how?  If we override it to be "Delete {0} Pipeline" then plugins without specific pronouns will end up saying ""Delete Multi-branch Pipeline Pipeline".   

Also not this same issue applies to the GitHub Organization Pipeline - Added documentation to JIRA, and updating this PR to fix that was well.

**Comment by stephenc** [comment]
Just call it `Delete`

**Comment by stephenc** [comment]
I am :-1: on embedding “Pipeline” in the pronoun for any Branch Source

**Comment by bitwiseman** [comment]
@rsandell @stephenc 
When it comes down to it, this issue was introduced by JENKINS-38987 not being completed for all branch sources.

Unless you strongly disagree, I propose we accept this change as it stands.  This will result in some low-pri-to-threoretical cases where the labels will be incorrect, but will address the more urgent problem of scaring users.
 
I will then open a follow up JIRA for properly wiring JENKINS-38987  through all branch sources and overriding the `Delete {0}` in branch-api.

**Comment by bitwiseman** [comment]
@stephenc 
I understand your objection and the reason.  It sounds like you feel the change you are suggesting is trivial, but frankly my jelly-fu is not strong enough to know where that change would go.  if you can make the change point me to an example of how to make it, that would  be great.

**Comment by bitwiseman** [comment]
@michaelneale @rsandell @stephenc 
Closing this in favor of https://github.com/jenkinsci/branch-api-plugin/pull/150

**Pull request closed without merging**
