### PR TITLE
[JENKINS-60353] Enable PR-204 workaround all the time

### PR DESCRIPTION
**Pull request by kshultzCB**
* JENKINS issue(s):
    * [JENKINS-60353](https://issues.jenkins-ci.org/browse/JENKINS-60353)
    * [JENKINS-54126](https://issues.jenkins-ci.org/browse/JENKINS-54126)
    * Possibly others.
* Description:
    * In short, this turns the workaround from [PR-204](https://github.com/jenkinsci/github-branch-source-plugin/pull/204) on all the time. 
    * There will be a very small uptick in the number of API requests used with this change in place - but only in the event of getting a `40*` response code back from GitHub
    * I don't expect this to solve all possible variants of the `Jenkinsfile not found` problem we've been battling for the last year and change. But some testing that @bitwiseman  and I worked on together, in the context of [JENKINS-60353](https://issues.jenkins-ci.org/browse/JENKINS-60353), shows that this does at least solve that particular case. The case can be seen in github-api-plugin PR-665, which provides a simple test to simulate the issue.
    * It is still possible to disable the workaround, by setting the system property `-Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.JENKINS_54126_WORKAROUND=false`.
* Documentation changes:
    * Probably no documentation needed, although mentioning this in a release note might be useful.
* Testing performed:
    * Existing unit tests all pass
    * Manual verification that running without this change produces the bug described in [JENKINS-60353](https://issues.jenkins-ci.org/browse/JENKINS-60353), while running with this change in place fixes the problem
* Users/aliases to notify:
    * @rsandell , who originally committed the workaround we're now enabling by default

### CODE REVIEW

**Comment by res0nance** [comment]
> -Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMProbe.JENKINS_54126_WORKAROUND=true

Disable should be setting it to `false` but the idea seems good. My instances have been plagued with this issue that seems impossible to replicate

**Comment by kshultzCB** [comment]
Good catch on that note. That was a copy/paste gone wrong, I’ve fixed it.

**Comment by runzexia** [comment]
Ready to merge this PR and draft a release?
I want to test it in my environment.

**Comment by bitwiseman** [comment]
This  work around as whole will not be needed once we upgrade to a version of github-api that includes this: https://github.com/github-api/github-api/pull/665 .
I hope to get that included in the next week, just in case I'll go ahead and merge this now.

**Pull request merged**
