### PR TITLE
Add an option to only build repositories that are private

### PR DESCRIPTION
**Pull request by wuurrd**
# Description
Add an option to only build repositories that are private

Based off https://github.com/jenkinsci/github-branch-source-plugin/pull/274/files

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Automated tests have been added to exercise the changes
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed

# Users/aliases to notify

### CODE REVIEW

**Comment by wuurrd** [comment]
@timja (or anyone else on the team - sorry to single you out like this) Any chance for a review?

**Comment by bitwiseman** [comment]
@wuurrd Yes, we need tests.

**Comment by wuurrd** [comment]
@bitwiseman sorry for the late reply - have added some tests - is there anything else you'd like?

**Comment by wuurrd** [comment]
@dwnusbaum @bitwiseman Anything I should change here? :smile_cat:

**Comment by psalaberria002** [comment]
Can someone have a look at this PR? Would be nice to have this feature. Thanks.

**Pull request merged**
