### PR TITLE
JENKINS-43755 - Update Github username regex to be less restrictive.

### PR DESCRIPTION
**Pull request by herzog31**

### CODE REVIEW

**Comment by dulvac** [comment]
+1!
Currently, the event doesn't match a repo if the owner is a two-letter name.

**Comment by telegrapher** [comment]
Thanks for this PR!

This issue is affecting us too!

**Comment by andreituicu** [comment]
+1!
We have this problem as well.

**Comment by dulvac** [comment]
@stephenc , thanks!

**Pull request merged**
