### PR TITLE
[JENKINS-47585] Implement lightweight changelog

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-47585](https://issues.jenkins-ci.org/browse/JENKINS-47585)

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
`@stephenc stephenc closed this a minute ago
 @stephenc stephenc reopened this 40 seconds ago`

 5 years in jenkins developers asking the question "how to rebuild PR?"

PS Thanks to observer hardcoded logic to deal only with this kind of PR functionality.

**Comment by stephenc** [comment]
@KostyaSha If I had permission to trigger builds on the ci server I'd just do that

**Comment by KostyaSha** [comment]
If observer wouldn't be so limited in functionality it will be able to get to ghprb-plugin or github-integration-plugin 4 years old functionality with message triggering. Firstly jenkins infra was locked with some closed source github trigger, now this observer.

**Comment by stephenc** [comment]
There is *nothing* stopping something listening to comments and firing builds in the normal `scheduleBuild` way.

**Comment by KostyaSha** [comment]
> There is nothing stopping something listening to comments and firing builds in the normal scheduleBuild way.

Beside that i should handle childObserver and duplicate part of existing logic and change event processing. That sounds like the same level of making MultiBranchProject with some Trigger API, but without multibranch.observer

**Pull request merged**
