### PR TITLE
[JENKINS-69482] Support for `ready_for_review` and `converted_to_draft` events

### PR DESCRIPTION
**Pull request by Dohbedoh**
# Description

Support for `ready_for_review` and `converted_to_draft` event action. See [JENKINS-69482](https://issues.jenkins.io/browse/JENKINS-69482)

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Automated tests have been added to exercise the changes
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [ ] Link to jenkins.io PR, or an explanation for why no doc changes are needed

# Users/aliases to notify

### CODE REVIEW

**Comment by Dohbedoh** [comment]
cc @jenkinsci/github-branch-source-plugin-developers

**Review by olamy — APPROVED** [review]

**Comment by iamtodor** [comment]
@olamy @Dohbedoh thank you for the solution, folks! 

Could you please point me to its usage? I walked thru the page https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-admin-guide/github-branch-source-plugin and I didn't find anything. Also, I asked a question in gitter chat, but got no answers.

If this is the wrong place to ask a question please let me know.

**Comment by iamtodor-fb** [comment]
to whom it may concern, in another PR there is usage https://github.com/jenkinsci/github-branch-source-plugin/pull/416#issuecomment-855282523

**Comment by iamtodor** [comment]
to whom it may concern, in another PR there is usage https://github.com/jenkinsci/github-branch-source-plugin/pull/416#issuecomment-855282523

**Pull request merged**
