### PR TITLE
Disable PR builds for public repos

### PR DESCRIPTION
**Pull request by kohsuke**
As things stand right now, PR builds for public repositories are unsafe,
due to the fact that anyone can submit a PR that modifies Jenkinsfile.

As far as I am concerned, this is a regression; it used to be that this
plugin did not automatically pick up PR builds.

There are various efforts in progress to address this in different ways,
and there are also other project recognizers that are considered that
can change the situation.

But until that happens, please disable this feature, for it's too easy
for people to "incorrectly" use this functionality with public
repositories and make their Jenkins instances vulnerable.

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees 
I consider this 2.0 release blocker

**Comment by kohsuke** [comment]
I thought about adding this into an option first, but given that other changes are planned to address this in a better way, I came to conclude that it is better not to.

If we make this into an user-visible option, the backward compatibility won't let us remove it.

**Comment by HRMPW** [comment]
I agree. We should disable PR support for public repos until we have support for trusted branches.

**Comment by jtnord** [comment]
:bee:

**Comment by recena** [comment]
:-1: I prefer to include an option (as it was planned) so that the user be able to choose if he wants to discover PR or not. In the inline help we can notice about the risks.

**Comment by recena** [comment]
It can be confused if pull requests are discovered only in private repositories.

**Comment by arthurschreiber** [comment]
For what it's worth, I also prefer an option for this.

**Comment by jtnord** [comment]
@recena as it stands this has been merged and is not releasable without a big gaping security whole.

So please don;t block this pending writing some new feature - get the secure thing done - (this PR) and do the configurable option thing as a follow up.

**Comment by recena** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Comment by recena** [comment]
I tried the PR....

```
Proposing workflow-helloworld
Connecting to GitHub using anonymous access
Looking up seville-jam/workflow-helloworld

  Getting remote branches...

    Checking branch master
      Jenkinsfile does not exist in this branch
    Does not meet criteria

  0 branches were processed

  Skipping pull requests for public repositories

Done examining seville-jam/workflow-helloworld
```

**Comment by jglick** [comment]
> There are various efforts in progress to address this in different ways

https://github.com/jenkinsci/scm-api-plugin/pull/5 specifically.

**Pull request merged**
