### PR TITLE
Revert "Specify a notification per job, so that we can distinctly see…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… merged and unmerged job results."

This reverts commit 5a98d2a885aa951087ba329acdc560bc1e6b7062.

Fixes https://issues.jenkins-ci.org/browse/JENKINS-36574

### CODE REVIEW

**Comment by medianick** [comment]
I get the benefit of having a job-specific status, as the original commit (that this reverts) was intending to do. My specific issue is due to use of the GitHub Organization Folder plug-in, which makes my job names dynamic (e.g., based on the branch or PR). A job-named status check is useless in that scenario. 

If the Org Folder plugin specifically could pass its own override of the status name into the Branch Source plugin, say, with the _folder_ name and repo name, I'd accept a "dynamic" status based on that.

**Comment by alcaeus** [comment]
Merely reverting the functionality is not an option. While I also require "constant" status strings, I do have multiple builds running per PR, so having the same context set for all builds is an equally breaking change.

**Comment by DeepDiver1975** [comment]
> Merely reverting the functionality is not an option. While I also require "constant" status strings, I do have multiple builds running per PR, so having the same context set for all builds is an equally breaking change.

But you can have only one Jenkinsfile in a repo and there is no option to allow an alternative Jenkinsfile in the configuration of the github orga.

How do you run multiple jobs in parallel?

Still having an option to name the status in the github orga config might be the best solution.

**Comment by alcaeus** [comment]
> How do you run multiple jobs in parallel?

It's not "multiple jobs" per se, but we test the branch head and PR merge head. Same Jenkinsfile, different code.

**Comment by DeepDiver1975** [comment]
> It's not "multiple jobs" per se, but we test the branch head and PR merge head. Same Jenkinsfile, different code.

Ah - I see. Thanks for the clarification.

What about building the context name similar to travis-ci

bildschirmfoto von 2016-07-25 10-17-33

We can have something like

continuous-integration/jenkins-ci/pr-merged
continuous-integration/jenkins-ci/pr-unmerged
continuous-integration/jenkins-ci/branch

**Comment by alcaeus** [comment]
The best solution, IMO, is if we could override the context in this configuration panel for the project:
image

That way, the developers could choose to use the current context "Jenkins job <jobname>", they could change it to a fixed context for each option (similar to the travis solution) and you could still decide to override it if you want (potentially giving all jobs the same context with the obvious trouble that it could cause).

**Comment by KostyaSha** [comment]
That lessons were already learned in 2 or 3 github plugins, later you will start talking about specifying urls for contexts.

**Comment by DeepDiver1975** [comment]
> That lessons were already learned in 2 or 3 github plugins, later you will start talking about specifying urls for contexts.

@KostyaSha What are you trying to tell us? Sorry I don't understand your comment.

Is this all non-sense from your point of view?
What would be your approach to solve this issue?

Thanks

**Comment by KostyaSha** [comment]
@DeepDiver1975 just monitoring how this plugin re-inventing functionality of other plugins where community already discussed everything.

**Comment by DeepDiver1975** [comment]
So - how to move on @jglick may I drag your attention here? THX

**Comment by alcaeus** [comment]
> just monitoring how this plugin re-inventing functionality of other plugins where community already discussed everything.

I'm open to using a different bundle if you can suggest one that provides the functionality I require 😃

**Comment by KostyaSha** [comment]
> I'm open to using a different bundle if you can suggest one that provides the functionality I require 😃

I didn't check how it works this this plugin, but latest github-plugin allows setting and controlling statuses manually (as step with clear settings).

**Comment by mikedougherty** [comment]
The [github plugin](https://github.com/jenkinsci/github-plugin) uses [`GithubProjectProperty.displayName`](https://github.com/jenkinsci/github-plugin/blob/44a87816b187bd21a32e7942f3830ca3f6fbfa45/src/main/java/com/coravy/hudson/plugins/github/GithubProjectProperty.java#L35-L42) as the context for the commit status; it seems reasonable to use this if present or something else (`"Jenkins"` ?) as a fallback.

**Comment by docwhat** [comment]
I pushed up PR #65 which makes it match what travis and friends do.

It doesn't break out the `pr-merged` and `pr-unmerged` mention by @DeepDiver1975 ... in part because I'm not sure what they are.

Also the detection for PR or not-PR is hacky, but I didn't see any way to ask the job itself whether it was a Pull Request or not; e.g. a `job.isPR()` method or something.

**Comment by alcaeus** [comment]
About merged/unmerged, see the screenshot I attached above. Those are all builds that can be triggered for a single branch. Some of these may be duplicate (e.g. PR unmerged is normally equal to the branch head) but they can still be run. Not sure how to deal with those though.

**Comment by docwhat** [comment]
@alcaeus: Wow, those are confusing... 

I'm trying to understand those options.
If I understand it, though, I think the UI would be better like this:

* [x] build branches
* [x] build PRs from from this repo
    * Merge with HEAD first
    * Build as it exists in the PR
* [x] build PRs from a forked repo
    * Merge with HEAD first
    * Build as it exists in the PR

The second levels would be drop down to chose how each of the PR types work.

I'm not sure what the difference is between "Build origin branches also filed as PRs" and "Build origin PRs (unmerged head)" -- Is the only difference the status check context name and whether it appears in "Branches" vs. "Pull Requests" in Jenkins?

**Comment by alcaeus** [comment]
> I'm not sure what the difference is between "Build origin branches also filed as PRs" and "Build origin PRs (unmerged head)" -- Is the only difference the status check context name and whether it appears in "Branches" vs. "Pull Requests" in Jenkins?

Yes, I'm not sure why you'd want to build the unmerged head for a PR since that would be the same as the head of the branch the PR is originating from. I agree with you, those options are too confusing.

**Comment by jglick** [comment]
Superseded by #68.

**Pull request closed without merging**
