### PR TITLE
[JENKINS-33623] Proxy configured in a wrong way

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-33623](https://issues.jenkins-ci.org/browse/JENKINS-33623)

- [x] Removed unused `import`
- [x] Clean up of unused code after https://github.com/jenkinsci/github-branch-source-plugin/pull/54
- [x] Fix the `Proxy` configuration

@reviewbybees 

Thank @schulzh for reporting the issue.

### CODE REVIEW

**Comment by recena** [comment]
@schulzh What do you think as alternative to https://github.com/jenkinsci/github-branch-source-plugin/pull/48?

**Comment by schulzh** [comment]
@recena It looks like a good solution

**Comment by recena** [comment]
@schulzh My first option was to use your PR but I wanted to clean up some details. At any rate, thank you so much for your work.

**Comment by amuniz** [comment]
:bee:

**Comment by freeman** [comment]
Hi,

I really want to use this plugin but this fix is blocking me at the moment. Any ETA on its release ?

Thanks for the great work on the github integration story in Jenkins !

**Comment by freeman** [comment]
By the way I tested it by compiling the master branch and deploying it and it works beautifully.

**Pull request merged**
