### PR TITLE
Make common traits consistent with bitbucket-branch-source-plugin

### PR DESCRIPTION
**Pull request by darxriggs**
Also see https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/256.

### CODE REVIEW

**Comment by bitwiseman** [comment]
@darxriggs Love the work you're doing, but could you make the formatting/comment changes in a separate commit from other code changes?

**Comment by darxriggs** [comment]
Now the merge conflict is resolved and the commits split as suggested.

**Comment by bitwiseman** [comment]
@darxriggs  
Looks good. Are there tests for that exercise your change?

**Comment by darxriggs** [comment]
Yes, these minimal changes are already covered by existing tests.

**Pull request merged**
