### PR TITLE
[JENKINS-67597] repo search topic: set page size

### PR DESCRIPTION
**Pull request by jetersen**
# Description

Increase page size to hopefully fix 
A brief summary describing the changes in this pull request. See 
[JENKINS-67597](https://issues.jenkins-ci.org/browse/JENKINS-67597) for further information. 

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [ ] Automated tests have been added to exercise the changes
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verify that the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

# Documentation changes
- [x] Link to jenkins.io PR, or an explanation for why no doc changes are needed

# Users/aliases to notify

### CODE REVIEW

**Comment by jetersen** [comment]
@bitwiseman Hi the test for `testAgentRefresh` has been shown to fail locally and on Jenkins CI.

https://github.com/jenkinsci/bom/pull/737

Not sure what has changed to cause the test failure.

**Review by car-roll — APPROVED** [review]

**Comment by timja** [comment]
:shipit: ?

**Comment by car-roll** [comment]
@timja sorry, I remember waiting for this build to go green, then I completely forgot about it 😞

**Comment by timja** [comment]
> @timja sorry, I remember waiting for this build to go green, then I completely forgot about it 😞

Enable automerge? 😉

**Pull request merged**
