### PR TITLE
Possible fix for [JENKINS-41246] Branch scanning fails when PR refer to a deleted fork

### PR DESCRIPTION
**Pull request by sgtcoolguy**
https://issues.jenkins-ci.org/browse/JENKINS-41246

If a PR is opened from a fork of the main repository and the fork is then deleted, the PR can stick around and the plugin will be unable to handle this PR. Specifically, the fork now has a null repository reference and the code attempts to grab the fork's owner to determine if the PR is from a trusted collaborator.

This manifests itself as an NPE like so:

```
ERROR: Failed to create or update a subproject Pydev
java.lang.NullPointerException
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.doRetrieve(GitHubSCMSource.java:571)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:451)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:254)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:260)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1153)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1168)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.add(GitHubSCMNavigator.java:459)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:319)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:398)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:219)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:141)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:849)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

You can test this against a PR like https://api.github.com/repos/aptana/Pydev/pulls/56 where this was breaking scanning. 

Note that this PR is not tested by me, but I believe does address the issue. The only complication I can foresee is if a PR can stick around after a user deletes their account as well. In that case, we'll get another NPE likely.

⚠️  Note that this has another side effect, which I think is to correct grabbing the collaborator name. This will now use the name of the user who filed the PR as the collaborator to check - rather than the owner of the repo the changes come from. I don't think they'd often differ under normal workflows, but this has changed with this PR.

### CODE REVIEW

**Comment by muhfuhcaw** [comment]
You are absolutely correct that the plugin throws another NPE if a user deletes their account *or* a github user loses access to a private repository, as is often the case when engineers leave a company and their github account access is revoked from that company's private repo. Is there any sane way to account for this use case as well?

**Comment by Santiclause** [comment]
Just ran in to this one. If this solution still has the possibility of an NPE, just add some additional guards in front of it. I think it's a pretty safe assumption that if an account is deleted, they're no longer trusted

**Comment by sgtcoolguy** [comment]
@muhfuhcaw Do you have the link to the JSON for the case you're referencing? I don't have any reference PRs where the user deleted their account to try and look at to determine what exactly would be null here.

**Comment by sgtcoolguy** [comment]
cc @stephenc

**Comment by muhfuhcaw** [comment]
@sgtcoolguy Can you clarify what json payload you're after from the github API? I have an offending PR on hand but I'm not familiar with this plugin code, I just ran into this issue and went hunting.

**Comment by sgtcoolguy** [comment]
@muhfuhcaw I shared one above: https://api.github.com/repos/aptana/Pydev/pulls/56

Basically the structure is https://api.github.com/repos/<org/owner>/<repoName>/pulls/<pr-number>

But if it's a private repo, then only you may be able to access the URL.

**Comment by muhfuhcaw** [comment]
@sgtcoolguy Yeah, it'll only be accessible to me. You could re-create the use-case by accessing a private github repo or setting one up, then forking the private repo and issue a PR against the privaate repo, then revoke your privileges to the repository with your PR still open. It's a lot of work, so we may look into it soon ourselves since it's a problem that affects us and we can more easily test it.

**Comment by stephenc** [comment]
Looks like I'm getting approved to spend time back on the branch sources as the driver that took me away these past couple of weeks is due to wrap up

**Comment by prakashsurya** [comment]
Hi, I've recently run into this issue as well. Is there anything I can do to help get this merged?

**Comment by stephenc** [comment]
I claim the issue was fixed in the changes for JENKINS-43507, the issue should not be present with 2.2.2 of the GHBS plugin

**Pull request closed without merging**
