### PR TITLE
[JENKINS-34237] GH Org. and GH User Accounts are searched using insensitive case

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-34237](https://issues.jenkins-ci.org/browse/JENKINS-34237)

@reviewbybees

### CODE REVIEW

**Comment by armfergom** [comment]
LGTM 🐝

**Comment by svanoort** [comment]
🐝 for me too.

**Comment by amuniz** [comment]
:bee: Although, probably implementing `equals` [here](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHPerson.java) would be the right place to fix it.

**Comment by recena** [comment]
@amuniz I thought the same but I have to discuss about it with @kohsuke

**Pull request merged**
