### PR TITLE
[JENKINS-57014] Deployment webhooks

### PR DESCRIPTION
**Pull request by philmadden83**
We currently use the existing GH Events for our CI pipeline to compile and provide feedback on our codebase changes. We would like to extend the functionality to trigger a pipeline based upon the creation of a deployment within GitHub. Deployments are how we signify that we would like to release a branch/sha/tag to production.

Unlike adding a specific comment, using a specific tag or creating a PR; deployments give us an audit trail of what was pushed and when alongside the code that was pushed.

### CODE REVIEW

**Comment by bitwiseman** [comment]
@philmadden83 could you talk a bit more about why this is needed?  Is there a JIRA for this?

**Comment by philmadden83** [comment]
@bitwiseman I don't believe there is a Jira for this. If you could kindly point me to the appropriate place to create a ticket for this I shall.

The short of it is: We would like to trigger pipelines upon the creation of a GitHub deployment.

The long of it is: We currently use the existing GH Events for our CI pipeline to compile and provide feedback on our codebase changes. We would like to extend the functionality to trigger a pipeline based upon the creation of a deployment within GitHub ([docs](https://developer.github.com/v3/repos/deployments/)). Deployments are how we signify that we would like to release a branch/sha/tag to production.

Unlike adding a specific comment, using a specific tag or creating a PR; deployments give us an audit trail of what was pushed and when alongside the code that was pushed.

**Comment by philmadden83** [comment]
@bitwiseman, certainly. I shall include a test for this change.

**Comment by bitwiseman** [comment]
@philmadden83 
Create an issue here: https://issues.jenkins-ci.org/

**Comment by philmadden83** [comment]
@bitwiseman I have created the issue: https://issues.jenkins-ci.org/browse/JENKINS-49259

**Comment by philmadden83** [comment]
@bitwiseman Unfortunatley I cannot see this working (looking for suggestions on this). The main issue is with the `MultiBranchProject` within the branch-api-plugin, specifically [this](https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/MultiBranchProject.java#L1540).

The `MultiBranchProject` does not treat webhooks as idempodent events. It is keeping a record of the git ref for the last triggered build of a project and prevents a build from occurring if the the same git ref is recieved multiple times. 

Enabling deployment webhooks means we would be recieving two webhook events for the same git ref; one push event for a repo change, and another to deploy that _same_ change ref.

**Comment by bitwiseman** [comment]
@philmadden83  
So, you'd like two pipeline runs to be triggered but only one is being triggered?

**Comment by philmadden83** [comment]
@bitwiseman 
correct.

> Perhaps it should check the event type as well?

I had the same thought but I figured we _may_ want to deploy / redeploy the same thing in case of a deployment failure, or we just want to force the last deployment to refresh instances.

I'm currently thinking about making it possible to toggle idempodent handling of SCMEvents on or off in the branch-api-plugin (default being off)

**Comment by bitwiseman** [comment]
@philmadden83 What about turning it off specifically for Deployment events?

**Comment by philmadden83** [comment]
@bitwiseman I like the sound of that. It would require the branch-api-plugin to depend on the kohsuke's github api though. Any concerns about introducing a circular dependency?

**Comment by bitwiseman** [comment]
@philmadden83 
Well, yeah, let's not do the circular dependency. Can you make that part override-able from this plugin? 
(What part is it?)

**Comment by philmadden83** [comment]
@bitwiseman
> Can you make that part override-able from this plugin?
I don't believe so. This will have to change the logic within the branch-api-plugin

**Comment by bitwiseman** [comment]
@philmadden83 
I think I see the problem - if we're subscribed to multiple event types we might get one for branch another for tag, and another for deploy, and generally we don't want to build again. 

The funny thing is that the branch-api-plugin [where you pointed](https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/MultiBranchProject.java#L1540) is only checking the last build.  As long as something else builds between the two events it will build again.  😕 

So, purely for testing, you could push one more commit after the one you want to deploy, let it build, and then do the deploy.  🙃 

As to making some part overridable - your are allowed to refactor code into new methods and then override those.   I'm saying it's the right path, but we definitely can't take a github dependency in branch-api, so I'm open to alternatives. 😄

**Comment by philmadden83** [comment]
@bitwiseman 
yes. You've nailed it. 

So I _could_ issue a `git commit --amend --no-edit` to just get a new sha _but_ this will actually trigger a build for the new sha putting me in the same situation 🙃

**Comment by bitwiseman** [comment]
@philmadden83  
Do you need help here?  Are you blocked?

**Comment by philmadden83** [comment]
@bitwiseman sorry for the delay in working on this.

I see you have started progress on it. I am happy to assist or take ownership of this.

**Comment by bitwiseman** [comment]
@philmadden83  I started progress to mark that you are doing it. 😄

**Comment by philmadden83** [comment]
@bitwiseman haha, ok. I'll pick it back up

**Comment by bitwiseman** [comment]
This branch was deleted.  Closing this PR, maybe someone will pick this up later.

**Pull request closed without merging**
