### PR TITLE
Added PULL_REQUEST_REVIEW_COMMENT event trigger to webhook

### PR DESCRIPTION
**Pull request by nitinsurana**
https://issues.jenkins-ci.org/browse/JENKINS-53694

### CODE REVIEW

**Comment by dmatej** [comment]
I'm not sure if it is enough ... it would build after each comment without filtering?

**Comment by nitinsurana** [comment]
I believe jenkins `quietPeriod` feature would take care of it.

**Comment by nitinsurana** [comment]
```
Pull request reviews
Pull request review comments
```
May be we should add both events to webhooks.

**Comment by rsandell** [comment]
I'm a bit uncertain of the consequences of adding this event

**Comment by kevindelord** [comment]
Could we filter the comments? Maybe with the usual `ok to test`  ?

**Comment by jglick** [comment]
I do not understand the purpose of this PR. Jenkins now registers itself to receive notifications of the new event type…but there is no `GHEventsSubscriber` defined in this plugin which would actually pay attention to it. So as far as I can tell, this does nothing other than route extra traffic to Jenkins.

To trigger builds based on other conditions would require additional logic, which can and should be defined in other plugins.

So I think this should be reverted. The associated issue is still open.

**Pull request merged**
