### PR TITLE
[JENKINS-33530] Remove unnecessary block against PR's from the origin…

### PR DESCRIPTION
**Pull request by TheJefe**
… repo

I do not see any reason to not build PR's that our submitted from the
origin repo.

### CODE REVIEW

**Comment by KostyaSha** [comment]
Deleting/adding cases wouldn't solve all use cases. I see no reason to not have normal configuration for end users or not providing APIs for plugins that could implement normal configurations.

**Comment by recena** [comment]
:-1: My preference is to provide an option from the UI.

**Comment by TheJefe** [comment]
To me this implements the normal case, not add an edge case.  This is merely a bug fix, not a new feature. I would need much more context to make configurable options.

**Comment by michaelneale** [comment]
@recena I think this SHOULD be enabled, possibly by default, as people often to PRs from forks vs origin interchangably in 2016. This seems related to https://issues.jenkins-ci.org/browse/JENKINS-33161

**Comment by TheJefe** [comment]
Rebased to resolve the merge conflicts

**Comment by recena** [comment]
@michaelneale My preference is to allow the build of PR from origin but including an option the UI. The user can choose the behavior.

**Comment by jglick** [comment]
:-1:, the current behavior is intentional. JENKINS-33161 remains valid but needs to be done differently.

**Comment by recena** [comment]
@jglick Do not agree if we include an option in the UI to manage this behavior?

**Comment by TheJefe** [comment]
@jglick , can you elaborate on why the current behavior is intentional? From git history and google group stuff, the best I could find was this was implemented to reduce the risk of a malicious branch getting built.   However, building from origin should be a safe thing.  If you have access to origin, you have access to everything already.  With that in mind, maybe this restriction does have a purpose, and there are just bad commit messages that missed describing the purpose of this specific restriction.  So can you explain the purpose?

**Comment by Pursuit92** [comment]
I'm in agreement with @TheJefe. Pull requests are pull requests, and it's quite common for companies to work out of a single private repository and submit pulls from the same origin.

**Comment by michaelneale** [comment]
I believe the downside of this is that there would be a branch build for the origin branch, and then another for the PR (and they will appear to be unrelated to each other): https://issues.jenkins-ci.org/browse/JENKINS-33161 desires to solve this by proposing that the origin branch be supressed while the PR is open (at least if I read it correctly). But clearly this is causing people some headaches, as origin PRs are pretty common.

**Comment by recena** [comment]
Basically, we need to address this if we can run *Branch per feature* and work only with the main repo not forked repositories (involves PR from them).

**Comment by recena** [comment]
@michaelneale 

> But clearly this is causing people some headaches, as origin PRs are pretty common.

These headaches can be avoided easily using forked repositories.

**Comment by KostyaSha** [comment]
> These headaches can be avoided easily using forked repositories.

So you want people to force change their flows?

**Comment by michaelneale** [comment]
@recena yes - but people are increasingly using branches instead of forks. Forks were popular originally as that is all you could do with PRs on github. That changed some years ago. However with larger teams, forks are problematic and unnecessary. People still want to use a pull request based flow but by having branches they can see what is in progress before a pull request is open.

**Comment by recena** [comment]
@KostyaSha 

> So you want people to force change their flows?

No, I don't. It is only something temporal until providing a solution.

**Comment by recena** [comment]
@michaelneale

> ... people are increasingly using branches instead of forks.

I don't have information about it but anyway, I **agree** with we have to support PR from origin. I hope to address this soon.

**Comment by KostyaSha** [comment]
Job generator should generate jobs with the minimal DEFAULT configuration, then users should have ability change (override) it. All checkboxes should be tri-state then. Plus job should have ability to work with a lot of existing plugins (missing API atm). Only in this case IMHO this job type and idea would work for real world users.

**Comment by recena** [comment]
@KostyaSha My initial idea is to manage this behavior through a configuration option. _Do you want to allow PR build from origin?_ By default, _yes_.

The key part is how to manage the jobs associated to the branch and its PR:

1. For the branch: we are building the `head` of this branch
1. For the PR associated to this branch: we are building the `merged_commit` of the PR.

This is what I have in my head.

**Comment by KostyaSha** [comment]
Travis builds both by default. In branch you build a real commit state (`head`), pr usually building merged state (but depends on project flows) (and travis sucks and hardcodes it). This plugin hardcodes everything and provides 5% of features available in 2 PR plugins.  I don't understand why are you thinking about what enable or not, just make it optional/configurable for users.

**Comment by KostyaSha** [comment]
> For the PR associated to this branch: we are building the merged_commit of the PR.

Yes, but many people doing merges themselves in job internals... No it really impossible to describe all cases for hard coding in code. Feel free to ignore my comments and continue re-inventing things.

**Comment by recena** [comment]
@KostyaSha Thanks for your feedback.

**Comment by TheJefe** [comment]
>These headaches can be avoided easily using forked repositories.

What about private Repos? That solution does not seem right for private Repos

**Comment by recena** [comment]
@TheJefe Why not?

**Comment by TheJefe** [comment]
Because I thought you could not fork a private repo, and keep it private.  I have just discovered that is incorrect.

**Comment by recena** [comment]
@TheJefe Yes you can do it.

**Comment by michaelneale** [comment]
@TheJefe yes forking private repos is a little bit terrible in ways people don't realise. For example, if you fork a private repo and someone deletes the upstream, your fork is deleted.

**Comment by michaelneale** [comment]
@recena the behaviour you describe sounds perfect.

**Comment by KostyaSha** [comment]
> bit terrible in ways people don't realise. For example, if you fork a private repo and someone deletes the upstream, your fork is deleted.

That's perfect way, people still would have local checkout.

**Comment by michaelneale** [comment]
@KostyaSha well - it does teach people that git is a distributed version control and never for forget that, yes ;)

**Comment by amuniz** [comment]
:+1: to add a configurable option to enable/disable PRs from origin.

:-1: to this PR.

**Comment by jglick** [comment]
Agreed.

Anyway the representation of `SCMRevision`s in this plugin is simply wrong and needs to be rewritten to make options like this be supportable in the right way.

**Comment by recena** [comment]
@jglick I'd appreciate if you share your thoughts in a Jira issue so that we can discuss about possible solutions. In my plan is to address this feature.

**Comment by michaelneale** [comment]
I don't like the thinking of "just add another option and leave it up to the user" - its how we end up with a bad experience. It is ok if things are thought about and the default is clear and this option can be hidden away.

**Comment by amuniz** [comment]
> It is ok if things are thought about and the default is clear and this option can be hidden away.

Yes. Probably this option should go in the _Advanced_ section (hidden by default) with a sensible default (ignore PRs from origin by default IMHO).

**Comment by recena** [comment]
It is not easy to determine the behavior. In this cases I always follow the [80-20 rule](http://c2.com/cgi/wiki?EightyTwentyRule). I try to be focused on 80% of the use cases.

**Comment by TheJefe** [comment]
Rebased to remove merge conflicts

**Comment by michaelneale** [comment]
@recena right, the default behavior people expect is that Jenkins knows about PRs no matter where they come from.

**Comment by ywen** [comment]
When we use Jenkins for a company with private repos on github. Most likely all the PRs will come from origin. I think this is a "80" use cases for private git repos.

**Comment by michaelneale** [comment]
@ywen yes agree - this will happen, just not clear how just yet. I agree the most common case especially for private repos is origin PRs. For open source they tend to be forks, which I think colours peoples opinion. 

cc @amuniz @recena - I don't think you are seeing the non open source use case. 

Given that even as it is now, if you open an origin PR, you do get the status set on the PR in github, but in Jenkins, it is unaware that a pull request is open, its just a branch of it, which looks a bit embarrasing.

**Comment by chinshr** [comment]
This would be a nifty change for building against our internal repos. @TheJefe How do I integrate your fork into Jenkins (maven/config)?

**Comment by TheJefe** [comment]
@chinshr 

1. clone down this repo
2. build the plugin, typically `mvn install` will do this. For more info see https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial
3. then upload the built hpi to your jenkins plugin page

**Comment by chinshr** [comment]
@TheJefe, thanks!

**Comment by jglick** [comment]
Superseded by #60.

**Comment by ryanpeach** [comment]
Is there any reason this would still be occuring on latest jenkins/jenkins helm chart? Using job-dsl like so:

```
multibranchPipelineJob('{{ .name }}') {
    branchSources {
        github {
            id('{{ randAlphaNum 5 }}') // IMPORTANT: use a constant and unique identifier
            checkoutCredentialsId('GithubUser')
            scanCredentialsId('GithubUser')
            repoOwner('OnScale')
            repository('{{ .name }}')
            includes('master main release/* PR-*')
            excludes('')
        }
    }
}
```

**Comment by ryanpeach** [comment]
Found it here:

https://github.com/jenkinsci/github-branch-source-plugin/blob/923184ce70fc84252937b8d08872f666efcc288b/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L1229-L1236

Looks like I need a strategy

**Comment by ryanpeach** [comment]
This worked for me:

```
multibranchPipelineJob('{{ .name }}') {
    branchSources {
        branchSource {
            source {
                github {
                    id('{{ randAlphaNum 5 }}') // IMPORTANT: use a constant and unique identifier
                    credentialsId('Github')
                    repoOwner('ryanpeach')
                    repository('{{ .name }}')
                    repositoryUrl('https://github.com/ryanpeach/{{ .name }}.git')
                    configuredByUrl(true)
                    traits {
                        gitHubBranchDiscovery {
                            // All branches
                            strategyId(3)
                        }
                        gitHubPullRequestDiscovery {
                            // Merging the pull request with the current target branch revision
                            strategyId(1)
                        }
                        headWildcardFilter{
                            includes('master main PR-*')
                            excludes('')
                        }
                    }
                }
            }
        }
    }
}
```

**Pull request closed without merging**
