### PR TITLE
Adjustments

### PR DESCRIPTION
**Pull request by jglick**
According to upstream https://github.com/jenkinsci/cloudbees-folder-plugin/pull/20, https://github.com/jenkinsci/scm-api-plugin/pull/3, https://github.com/jenkinsci/branch-api-plugin/pull/8, https://github.com/jenkinsci/workflow-plugin/pull/220.

@reviewbybees esp. @stephenc

### CODE REVIEW

**Comment by amuniz** [comment]
:bee:
BTW How is this compiling? Did you deploy snapshots for upstreams?

**Comment by tfennelly** [comment]
:bee: 

Though the `discoverSources`/ `visitSources` change seems to be bin-incompatible.

**Comment by jglick** [comment]
> Did you deploy snapshots for upstreams?

Yes, I did start.

> the `discoverSources`/ `visitSources` change seems to be bin-incompatible.

Yes of course, but there has never been a release of the API to begin with.

**Comment by tfennelly** [comment]
> Yes of course, but there has never been a release of the API to begin with.

Fair enough. Thanks and sorry for the noise.

**Comment by stephenc** [comment]
:bee:

**Pull request merged**
