### PR TITLE
[FIXED JENKINS-52397] Hit-and-run fix attempt

### PR DESCRIPTION
**Pull request by stephenc**

### CODE REVIEW

**Comment by stephenc** [comment]
@rsandell can you take this one under your wings and see if it can be merged and released?

**Comment by stephenc** [comment]
@rsandell due to the communications error of copy&paste in slack, @stephen-badger has given it the once-over and said it looks ok

screenshot 2018-11-16 at 14 46 20

**Comment by got-root** [comment]
@rsandell any chance we could get a release cut with this fix in it? Pretty please! :pray:

**Comment by dohpaz42** [comment]
FYI, @rsandell, this issue with not being able to scan for tags is preventing branch deletion in Jenkins. Once the Discover Tags is removed from the workflow, the branches are then able to be deleted - in my case it was almost 200 stale branches (5.5GB on disk). However, that means not being able to discover tags, which is a part of our pipeline workflow. 

This has been waiting a release since mid-November. Is there any idea of an ETA on when the next release will be considered? It looks like the last activity was in early December.

**Comment by lifeofguenter** [comment]
I am in the exact same boat as @9ae8sdf76

**Pull request merged**
